apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nullus.secretName" . }}
  labels:
    {{- include "nullus.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | quote }}
  encryption-key: {{ .Values.secrets.encryptionKey | quote }}
