apiVersion: v1
kind: Service
metadata:
  name: {{ include "nullus.fullname" . }}-api
  labels:
    {{- include "nullus.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "nullus.api.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nullus.fullname" . }}-web
  labels:
    {{- include "nullus.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
  - port: {{ .Values.web.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "nullus.web.selectorLabels" . | nindent 4 }}
